[package]

name = "json_serve"
version = "0.0.1"
authors = [ "jfager@gmail.com" ]


[dependencies]
rustc-serialize = "*"
byteorder = "*"
openssl = "*"

[dependencies.multicast]
path = "../multicast"

[profile.dev]
debug = false
